pub enum Dir {
    Up,
    Down,
    Left,
    Right,
    UpLeft,
    UpRight,
    DownLeft,
    DownRight,
    HorseUpLeft,
    HorseUpRight,
    HorseRightUp,
    HorseRightDown,
    HorseDownRight,
    HorseDownLeft,
    HorseLeftDown,
    HorseLeftUp,
}